version: '3.3'
services:
  db:
    image: mysql:8.0.18
    restart: always
    environment:
      MYSQL_DATABASE: 'jasoft_listdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'dev'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'jasoft102579'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'jasoft102579'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db-list:/var/lib/mysql
# Names our volume
volumes:
  db-list: