openapi: 3.0.0
info:
  version: 1.0.0
  title: Grocery List API
  description: List API designed to facilitate shopping lists
servers:
- url: https://www.groceries.io/api/v1
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    $ref: components/schemas.yaml
  parameters:
    $ref: components/parameters.yaml
  responses:
    $ref: components/responses.yaml

security:
- BasicAuth: []

paths:
  "/lists":
    get:
      description: Returns all current shopping lists
      parameters:
      - "$ref": "#/components/parameters/PageLimit"
      - "$ref": "#/components/parameters/PageOffset"
      - "$ref": "#/components/parameters/UserID"
      - name: store
        in: query
        description: Filters the returned list by store name
        schema:
          type: string
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/listArray"
        '400':
          "$ref": "#/components/responses/400Error"
        '500':
          "$ref": "#/components/responses/500Error"
    post:
      description: Adds a list to the lists collection
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/listNoIdArray"
      responses:
        '204':
          description: Lists added to List Collection
        '400':
          "$ref": "#/components/responses/400Error"
        '500':
          "$ref": "#/components/responses/500Error"
  "/lists/{listID}":
    get:
      description: Get a list by list id
      parameters:
      - name: listId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successfully returned a list
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/list"
    put:
      description: Updates or inserts a list
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/listNoId"
      responses:
        '204':
          description: List Updated or Inserted
    delete:
      responses:
        '204':
          description: List deleted
  "/items":
    get:
      description: Get list of items form the server
      responses:
        '200':
          description: Successfully returned a collection of items
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/itemArray"
        
    post:
      description: Adds a list of items
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/itemNoIdArray"
      responses:
        '204':
          description: Items created