PageLimit:
  name: limit
  in: query
  description: Limits the number of items per page
  schema:
    type: integer
PageOffset:
  name: offset
  in: query
  description: Specifies the page number to display
  schema:
    type: integer
UserID:
  name: user_id
  in: query
  description: User ID info for list request
  schema: integer